title: "L'Atelier des Médias"
description: "Le 1er espace de coworking Lyonnais associatif"
meta_robots: noindex
lang: fr
locale: fr_FR

liquid:
  error_mode: strict
  strict_filters: true

twitter:
  username: coworkinglyon

facebook:
  page: Coworkinglyon
  app_id: 106737945179435

linkedin:
  page: "l-atelier-des-m%C3%A9dias-coworking-lyon"

instagram:
  username: "atelierdesmedias_lyon"

exclude:
  - Makefile
  - Rakefile
  - "*.rb"
  - .github
  - "*.orig"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

collections:
  formulas:
    output: true
  coworkers:
    output: true
  events:
    output: true
  posts:
    output: true
    permalink: /blog/:title

pagination:
  enabled: true
  per_page: 8
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
