title: "L'Atelier des Médias"
description: "Le 1er espace de coworking Lyonnais associatif"
base_url: "adm"
meta_robots: noindex
lang: fr
locale: fr_FR

show_social_icons: true
twitter:
  username: coworkinglyon

facebook:
  page: Coworkinglyon
  #app_id: TODO

instagram:
  username: "atelierdesmedias_lyon"

#webmaster_verifications:
#  google: TODO
#  bing: TODO
#  facebook: TODO

exclude:
  - Makefile
  - sync.rb

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  coworkers:
    output: true
