title: "L'Atelier des Médias"
description: "Le 1er espace de coworking Lyonnais associatif"
base_url: "adm"
lang: fr
locale: fr_FR

twitter:
  username: coworkinglyon

facebook:
  page: Coworkinglyon

exclude:
  - Makefile
  - sync.rb

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  coworkers:
    output: true
