name: Lint

on: [pull_request]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          rubocop: true
          rubocop_command_prefix: bundle exec
          stylelint: true
